/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.organizadordetareas.Vista;

import com.mycompany.organizadordetareas.Controlador.Evento;
import com.mycompany.organizadordetareas.Controlador.Fecha;
//import com.mycompany.organizadordetareas.Controlador.GestorGeneral;
import com.mycompany.organizadordetareas.Controlador.Hora;
//import com.mycompany.organizadordetareas.Controlador.Usuario;
import com.mycompany.organizadordetareas.Controlador.Validadores;
import java.awt.Color;
import java.awt.Dimension;
// ._. (flag internacional pluggin)
/**
 *
 * @author Usuario
 */
public class CrearEvento extends javax.swing.JFrame {

    private MenuUsuario menuUs;
    //private GestorGeneral g;
    //private Usuario us;
    /**
     * Creates new form CrearEvento
     */
    public CrearEvento() {
        initComponents();
        setLocationRelativeTo(null);
        lblHoraX.setVisible(false);
        lblFechaX.setVisible(false);
        setLocation(400,500);
        setSize(1000,650);
        setMaximumSize(new Dimension(1000,650));
        setMinimumSize(new Dimension(1000,650));
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(55, 57, 63));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aceptar = new javax.swing.JButton();
        lblBienvenida = new javax.swing.JLabel();
        lblEvento = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        lblEvento1 = new javax.swing.JLabel();
        lblEvento2 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblEvento3 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        lblEvento4 = new javax.swing.JLabel();
        lblEvento5 = new javax.swing.JLabel();
        listPrio = new javax.swing.JComboBox<>();
        lblHoraX = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDD = new javax.swing.JTextField();
        txtMM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAAAA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblFechaX = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        aceptar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        aceptar.setBackground(new java.awt.Color(10, 135, 55));
        aceptar.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        aceptar.setForeground(new java.awt.Color(234, 234, 235));
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lorem Ipsum - App");
        setBackground(new java.awt.Color(2, 46, 89));

        lblBienvenida.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(234, 234, 235));
        lblBienvenida.setText("Nuevo Evento");
        lblBienvenida.setToolTipText("");

        lblEvento.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblEvento.setForeground(new java.awt.Color(234, 234, 235));
        lblEvento.setText("Nuevo Titulo:");

        txtTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(51, 51, 51));
        txtTitulo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTitulo.setToolTipText("Usa Tab para moverte mas rapido");
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtDescripcion.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(51, 51, 51));
        txtDescripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDescripcion.setToolTipText("Usa Tab para moverte mas rapido");
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        lblEvento1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblEvento1.setForeground(new java.awt.Color(234, 234, 235));
        lblEvento1.setText("Ingrese su Descripción:");

        lblEvento2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblEvento2.setForeground(new java.awt.Color(234, 234, 235));
        lblEvento2.setText("Ingrese el Lugar del Evento:");

        txtLugar.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtLugar.setForeground(new java.awt.Color(51, 51, 51));
        txtLugar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtLugar.setToolTipText("Usa Tab para moverte mas rapido");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("LOGO");

        lblEvento3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblEvento3.setForeground(new java.awt.Color(234, 234, 235));
        lblEvento3.setText("Ingrese la Hora:");

        txtHora.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtHora.setForeground(new java.awt.Color(51, 51, 51));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtHora.setToolTipText("Usa Tab para moverte mas rapido");
        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });

        lblEvento4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblEvento4.setForeground(new java.awt.Color(234, 234, 235));
        lblEvento4.setText("Prioridad:");

        lblEvento5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblEvento5.setForeground(new java.awt.Color(234, 234, 235));
        lblEvento5.setText("Ingrese la Fecha:");

        listPrio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listPrio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        listPrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPrioActionPerformed(evt);
            }
        });

        lblHoraX.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        lblHoraX.setForeground(new java.awt.Color(234, 234, 235));
        lblHoraX.setText("Hora Invalida (hh:mm)");
        lblHoraX.setToolTipText("");

        txtMin.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtMin.setForeground(new java.awt.Color(51, 51, 51));
        txtMin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMin.setToolTipText("Usa Tab para moverte mas rapido");
        txtMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(234, 234, 235));
        jLabel2.setText(":");

        txtDD.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtDD.setForeground(new java.awt.Color(51, 51, 51));
        txtDD.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDD.setToolTipText("Usa Tab para moverte mas rapido");
        txtDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDDActionPerformed(evt);
            }
        });

        txtMM.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtMM.setForeground(new java.awt.Color(51, 51, 51));
        txtMM.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMM.setToolTipText("Usa Tab para moverte mas rapido");
        txtMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMMActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(234, 234, 235));
        jLabel3.setText("/");

        txtAAAA.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtAAAA.setForeground(new java.awt.Color(51, 51, 51));
        txtAAAA.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAAAA.setToolTipText("Usa Tab para moverte mas rapido");
        txtAAAA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAAAAActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(234, 234, 235));
        jLabel4.setText("/");

        lblFechaX.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        lblFechaX.setForeground(new java.awt.Color(234, 234, 235));
        lblFechaX.setText("Fecha Invalida (hh/mm/aaaa)");

        cancelar.setBackground(new java.awt.Color(10, 135, 55));
        cancelar.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        cancelar.setForeground(new java.awt.Color(234, 234, 235));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        aceptar1.setBackground(new java.awt.Color(10, 135, 55));
        aceptar1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        aceptar1.setForeground(new java.awt.Color(234, 234, 235));
        aceptar1.setText("Aceptar");
        aceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(234, 234, 235));
        jLabel5.setText(":");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEvento)
                        .addGap(97, 97, 97)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEvento4)
                        .addGap(42, 42, 42)
                        .addComponent(listPrio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEvento1)
                                .addComponent(lblEvento2)))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEvento3)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel2)
                                .addGap(170, 170, 170)
                                .addComponent(lblEvento5)
                                .addGap(18, 18, 18)
                                .addComponent(txtDD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHoraX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFechaX)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAAAA, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(aceptar1)
                        .addGap(49, 49, 49)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEvento)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEvento1)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEvento2)
                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMin, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtDD, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtMM, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtAAAA, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(lblEvento5))
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEvento3)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraX)
                    .addComponent(lblFechaX))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEvento4)
                    .addComponent(listPrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar1)
                    .addComponent(cancelar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        txtTitulo.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void listPrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listPrioActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinActionPerformed

    private void txtDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDDActionPerformed

    private void txtMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMMActionPerformed

    private void txtAAAAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAAAAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAAAAActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        menuUs.setVisible(true);
        menuUs.releerEvento();
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        lblHoraX.setVisible(false);
        lblFechaX.setVisible(false);
        Validadores valid = new Validadores();
        String titulo = txtTitulo.getText();
        String descripcion = txtDescripcion.getText();
        
        String hora = txtHora.getText() + ":" + txtMin.getText();
        
        String fecha = txtDD.getText() + "/" + txtMM.getText() + "/" + txtAAAA.getText();
        
        String lugar = txtLugar.getText();
        int prioridad = Integer.parseInt(listPrio.getSelectedItem().toString());
        
        Hora horaVal = new Hora(0,0);
        Fecha fechaVal = new Fecha(0,0,0);
        
        if(!valid.validarHora(hora)){
            lblHoraX.setVisible(true);
        }else{
            String[] partesH = hora.split(":");
            int hh = Integer.parseInt(partesH[0]);
            int mm = Integer.parseInt(partesH[1]);
            horaVal = new Hora(hh,mm);   
        }
        
        if(!valid.validarFecha(fecha)){
            lblFechaX.setVisible(true);
        }else{
            String[] partesFV = fecha.split("/");
            int d = Integer.parseInt(partesFV[0]);
            int m = Integer.parseInt(partesFV[1]);
            int y = Integer.parseInt(partesFV[2]);
            fechaVal = new Fecha(d,m,y);
            menuUs.g.registrarEvento(new Evento(titulo,descripcion,horaVal,fechaVal,prioridad,lugar));
            menuUs.setVisible(true);
            this.dispose();
            menuUs.releerEvento();
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void aceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar1ActionPerformed
        lblHoraX.setVisible(false);
        lblFechaX.setVisible(false);
        Validadores valid = new Validadores();
        String titulo = txtTitulo.getText();
        String descripcion = txtDescripcion.getText();
        
        String hora = txtHora.getText() + ":" + txtMin.getText();
        
        String fecha = txtDD.getText() + "/" + txtMM.getText() + "/" + txtAAAA.getText();
        
        String lugar = txtLugar.getText();
        int prioridad = Integer.parseInt(listPrio.getSelectedItem().toString());
        
        Hora horaVal = new Hora(0,0);
        Fecha fechaVal = new Fecha(0,0,0);
        
        if(!valid.validarHora(hora)){
            lblHoraX.setVisible(true);
        }else{
            String[] partesH = hora.split(":");
            int hh = Integer.parseInt(partesH[0]);
            int mm = Integer.parseInt(partesH[1]);
            horaVal = new Hora(hh,mm);   
        }
        
        if(!valid.validarFecha(fecha)){
            lblFechaX.setVisible(true);
        }else{
            String[] partesFV = fecha.split("/");
            int d = Integer.parseInt(partesFV[0]);
            int m = Integer.parseInt(partesFV[1]);
            int y = Integer.parseInt(partesFV[2]);
            fechaVal = new Fecha(d,m,y);
            menuUs.g.registrarEvento(new Evento(titulo,descripcion,horaVal,fechaVal,prioridad,lugar));
            menuUs.setVisible(true);
            this.dispose();
            menuUs.releerEvento();
        }
    }//GEN-LAST:event_aceptar1ActionPerformed

    public void setMenuUs(MenuUsuario menuUs){
        this.menuUs = menuUs;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CrearEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton aceptar1;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblEvento1;
    private javax.swing.JLabel lblEvento2;
    private javax.swing.JLabel lblEvento3;
    private javax.swing.JLabel lblEvento4;
    private javax.swing.JLabel lblEvento5;
    private javax.swing.JLabel lblFechaX;
    private javax.swing.JLabel lblHoraX;
    private javax.swing.JComboBox<String> listPrio;
    private javax.swing.JTextField txtAAAA;
    private javax.swing.JTextField txtDD;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtMM;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
