/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.organizadordetareas.Vista;

import com.mycompany.organizadordetareas.Controlador.Fecha;
//import com.mycompany.organizadordetareas.Controlador.GestorGeneral;
import com.mycompany.organizadordetareas.Controlador.Hora;
import com.mycompany.organizadordetareas.Controlador.Tarea;
//import com.mycompany.organizadordetareas.Controlador.Usuario;
import com.mycompany.organizadordetareas.Controlador.Validadores;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author Usuario
 */
public class CrearTarea extends javax.swing.JFrame {

    private MenuUsuario menuUs;
    //private Usuario us;
    //private GestorGeneral g;
    /**
     * Creates new form CrearEvento
     */
    public CrearTarea() {
        initComponents();
        setLocationRelativeTo(null);
        lblHoraX.setVisible(false);
        lblFechaX.setVisible(false);
        setLocation(400,500);
        setSize(1000,600);
        setMaximumSize(new Dimension(1000,600));
        setMinimumSize(new Dimension(1000,600));
        setResizable(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(55, 57, 63));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        lblEvento = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblEvento3 = new javax.swing.JLabel();
        lblEvento4 = new javax.swing.JLabel();
        lblEvento5 = new javax.swing.JLabel();
        listPrio = new javax.swing.JComboBox<>();
        lblHoraX = new javax.swing.JLabel();
        lblFechaX = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        txtDD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAAAA = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        aceptar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lorem Ipsum - App");
        setBackground(new java.awt.Color(2, 46, 89));

        lblBienvenida.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(234, 234, 235));
        lblBienvenida.setText("Nueva Tarea");
        lblBienvenida.setToolTipText("");

        lblEvento.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblEvento.setForeground(new java.awt.Color(234, 234, 235));
        lblEvento.setText("Nuevo Titulo:");

        txtTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(51, 51, 51));
        txtTitulo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTitulo.setToolTipText("Usa Tab para moverte mas rapido");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(234, 234, 235));
        jLabel1.setText("LOGO");

        lblEvento3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblEvento3.setForeground(new java.awt.Color(234, 234, 235));
        lblEvento3.setText("Ingrese la Hora:");

        lblEvento4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblEvento4.setForeground(new java.awt.Color(234, 234, 235));
        lblEvento4.setText("Prioridad:");

        lblEvento5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblEvento5.setForeground(new java.awt.Color(234, 234, 235));
        lblEvento5.setText("Ingrese la Fecha:");

        listPrio.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        listPrio.setForeground(new java.awt.Color(234, 234, 235));
        listPrio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        listPrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPrioActionPerformed(evt);
            }
        });

        lblHoraX.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        lblHoraX.setForeground(new java.awt.Color(234, 234, 235));
        lblHoraX.setText("Hora Invalida");

        lblFechaX.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        lblFechaX.setForeground(new java.awt.Color(234, 234, 235));
        lblFechaX.setText("Fecha Invalida");

        txtHora.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtHora.setForeground(new java.awt.Color(51, 51, 51));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtHora.setToolTipText("Usa Tab para moverte mas rapido");
        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(234, 234, 235));
        jLabel2.setText(":");

        txtMin.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtMin.setForeground(new java.awt.Color(51, 51, 51));
        txtMin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMin.setToolTipText("Usa Tab para moverte mas rapido");
        txtMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinActionPerformed(evt);
            }
        });

        txtDD.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtDD.setForeground(new java.awt.Color(51, 51, 51));
        txtDD.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDD.setToolTipText("Usa Tab para moverte mas rapido");
        txtDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(234, 234, 235));
        jLabel3.setText("/");

        txtMM.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtMM.setForeground(new java.awt.Color(51, 51, 51));
        txtMM.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMM.setToolTipText("Usa Tab para moverte mas rapido");
        txtMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMMActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(234, 234, 235));
        jLabel4.setText("/");

        txtAAAA.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtAAAA.setForeground(new java.awt.Color(51, 51, 51));
        txtAAAA.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAAAA.setToolTipText("Usa Tab para moverte mas rapido");
        txtAAAA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAAAAActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(10, 135, 55));
        cancelar.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        cancelar.setForeground(new java.awt.Color(234, 234, 235));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        aceptar1.setBackground(new java.awt.Color(10, 135, 55));
        aceptar1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        aceptar1.setForeground(new java.awt.Color(234, 234, 235));
        aceptar1.setText("Aceptar");
        aceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEvento5)
                                    .addComponent(lblEvento3))
                                .addGap(175, 175, 175)
                                .addComponent(lblHoraX))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEvento)
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAAAA, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaX)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(197, 197, 197)
                                        .addComponent(jLabel1))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEvento4)
                                .addGap(42, 42, 42)
                                .addComponent(listPrio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelar)
                                .addGap(18, 18, 18)
                                .addComponent(aceptar1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEvento)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEvento3)
                    .addComponent(lblHoraX)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEvento5)
                            .addComponent(txtDD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMM, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtAAAA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(lblFechaX))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEvento4)
                            .addComponent(listPrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(96, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelar)
                            .addComponent(aceptar1))
                        .addGap(54, 54, 54))))
        );

        txtTitulo.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listPrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listPrioActionPerformed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinActionPerformed

    private void txtDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDDActionPerformed

    private void txtMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMMActionPerformed

    private void txtAAAAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAAAAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAAAAActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        menuUs.setVisible(true);
        menuUs.releerEvento();
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void aceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar1ActionPerformed
        lblHoraX.setVisible(false);
        lblFechaX.setVisible(false);
        Validadores valid = new Validadores();
        String titulo = txtTitulo.getText();
        
        String hora = txtHora.getText() + ":" + txtMin.getText();
        
        String fecha = txtDD.getText() + "/" + txtMM.getText() + "/" + txtAAAA.getText();
        
        int prioridad = Integer.parseInt(listPrio.getSelectedItem().toString());
        
        Hora horaVal = new Hora(0,0);
        Fecha fechaVal = new Fecha(0,0,0);
        
        if(!valid.validarHora(hora)){
            lblHoraX.setVisible(true);
        }else{
            String[] partesH = hora.split(":");
            int hh = Integer.parseInt(partesH[0]);
            int mm = Integer.parseInt(partesH[1]);
            horaVal = new Hora(hh,mm);   
        }
        
        if(!valid.validarFecha(fecha)){
            lblFechaX.setVisible(true);
        }else{
            String[] partesFV = fecha.split("/");
            int d = Integer.parseInt(partesFV[0]);
            int m = Integer.parseInt(partesFV[1]);
            int y = Integer.parseInt(partesFV[2]);
            fechaVal = new Fecha(d,m,y);
            menuUs.g.registrarTarea(new Tarea(titulo,horaVal,fechaVal,prioridad));
            menuUs.setVisible(true);
            this.dispose();
            menuUs.releerTarea();
        }
    }//GEN-LAST:event_aceptar1ActionPerformed

    public void setMenuUs(MenuUsuario menuUs){
        this.menuUs = menuUs;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar1;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblEvento3;
    private javax.swing.JLabel lblEvento4;
    private javax.swing.JLabel lblEvento5;
    private javax.swing.JLabel lblFechaX;
    private javax.swing.JLabel lblHoraX;
    private javax.swing.JComboBox<String> listPrio;
    private javax.swing.JTextField txtAAAA;
    private javax.swing.JTextField txtDD;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtMM;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
