/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.organizadordetareas.Vista;

import com.mycompany.organizadordetareas.Controlador.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Arrick
 */
public class EditarEvento extends javax.swing.JFrame {
    private Evento evento;
    private GestorGeneral g;
    private MenuUsuario menuUs;
    /**
     * Creates new form EditarEvento
     */
    public EditarEvento(Evento evento, GestorGeneral g) {
        this.evento = evento;
        this.g = g;
        initComponents();
        setSize(1000,600);
        setResizable(false);
        setLocationRelativeTo(null);
        modificar_titulo.setText(evento.getTitulo());
        modificar_descripcion.setText(evento.getDescripcion());
        modificar_hora.setText(evento.getHora().toString());
        modificar_fecha.setText(evento.getFecha().toString());
        modificar_lugar.setText(evento.getLugar());
        modificar_prioridad.setSelectedItem(Integer.toString(evento.getPrioridad()));
        horaNoValida.setVisible(false);
        fechaNoValida.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        modificar_titulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        modificar_descripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        modificar_lugar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        modificar_hora = new javax.swing.JTextField();
        modificar_fecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        modificar_prioridad = new javax.swing.JComboBox<>();
        cancelar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        horaNoValida = new javax.swing.JLabel();
        fechaNoValida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reescriba lo que desee editar:");

        jLabel2.setText("Titulo:");

        modificar_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_tituloActionPerformed(evt);
            }
        });

        jLabel3.setText("Descripción");

        modificar_descripcion.setToolTipText("");
        modificar_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_descripcionActionPerformed(evt);
            }
        });

        jLabel4.setText("Lugar:");

        modificar_lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_lugarActionPerformed(evt);
            }
        });

        jLabel5.setText("Hora (hh:mm) :");

        modificar_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_fechaActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha (dd/mm/aaaa)");
        jLabel6.setToolTipText("");

        jLabel7.setText("Prioridad:");

        modificar_prioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        cancelar.setText("Cancelar");

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        horaNoValida.setText("Hora no valida");

        fechaNoValida.setText("Fecha no valida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(horaNoValida)
                                .addComponent(jLabel7)))
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modificar_prioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modificar_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaNoValida)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(56, 56, 56)
                                        .addComponent(modificar_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(modificar_lugar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addComponent(modificar_descripcion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(modificar_titulo, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelar)
                .addGap(96, 96, 96)
                .addComponent(guardar)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(modificar_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(modificar_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(modificar_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(modificar_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horaNoValida)
                    .addComponent(fechaNoValida))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(modificar_prioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(guardar))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificar_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_tituloActionPerformed

    private void modificar_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_descripcionActionPerformed

    private void modificar_lugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_lugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_lugarActionPerformed

    private void modificar_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_fechaActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
          Validadores validar = new Validadores();
        horaNoValida.setVisible(false);
        fechaNoValida.setVisible(false);
        String titulo = modificar_titulo.getText();
        String descripcion = modificar_descripcion.getText();
        String lugar = modificar_lugar.getText();
        String hora = modificar_hora.getText();
        
        
        
        String fecha = modificar_fecha.getText();
        
        
        
        int prioridad = Integer.parseInt((String)modificar_prioridad.getSelectedItem());
        if(!validar.validarHora(hora)){
            horaNoValida.setVisible(true);
        }else{
            String[] partes = hora.split(":");
            int h = Integer.parseInt(partes[0]);
            int m = Integer.parseInt(partes[1]);
            Hora horaVal = new Hora(h,m);
            if(!validar.validarFecha(fecha)){
            fechaNoValida.setVisible(true);
            }else{
                String[] partesf = fecha.split("/");
            int dd = Integer.parseInt(partesf[0]);
            int mm = Integer.parseInt(partesf[1]);
            int aaaa = Integer.parseInt(partesf[2]);
            Fecha fechaVal = new Fecha(dd,mm,aaaa);
                g.modificarTitulo(titulo, evento.getTitulo(), 2);
                g.modificarDescripcion(descripcion, evento.getTitulo());
                g.modificarLugar(lugar, evento.getTitulo());
                g.modificarPrioridad(prioridad, evento.getTitulo(),2);
                g.modificarHora(horaVal, evento.getTitulo(), 2);
                g.modificarFecha(fechaVal, evento.getTitulo(), 2);
 
                menuUs = new MenuUsuario(g.getUsuario());
                menuUs.setVisible(true);
                this.dispose();
            }
        }        
    }//GEN-LAST:event_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
    
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel fechaNoValida;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel horaNoValida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField modificar_descripcion;
    private javax.swing.JTextField modificar_fecha;
    private javax.swing.JTextField modificar_hora;
    private javax.swing.JTextField modificar_lugar;
    private javax.swing.JComboBox<String> modificar_prioridad;
    private javax.swing.JTextField modificar_titulo;
    // End of variables declaration//GEN-END:variables
}
