/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.organizadordetareas.Vista;

import com.mycompany.organizadordetareas.Controlador.*;
import java.awt.Color;


/**
 *
 * @author Arrick
 */
public class IniciarSesion extends javax.swing.JFrame {
    private VentanaInicio v1;
    private OlvidasteContrasena olvCont;
    private GestorUser gestorUsuarios;
    private MenuUsuario menuUs;
    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        
        gestorUsuarios = new GestorUser();
        initComponents();
        setLocation(400,500);
        setSize(1000,700);
        setResizable(false);
        jLabel3.setVisible(false);
        bienvenido.setVisible(false);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(55, 57, 63));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bienvenido = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        campoContras = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        textoPregunta = new javax.swing.JLabel();
        textoPregunta1 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        cancelar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        nomUsuario.setBackground(new java.awt.Color(55, 57, 63));
        nomUsuario.setFont(new java.awt.Font("STXihei", 0, 16)); // NOI18N
        nomUsuario.setForeground(new java.awt.Color(234, 234, 235));
        nomUsuario.setToolTipText("");
        nomUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 234, 235)));
        nomUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("STXihei", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(234, 234, 235));
        jLabel3.setText("Credenciales incorrectos");

        bienvenido.setFont(new java.awt.Font("STXihei", 1, 36)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(234, 234, 235));
        bienvenido.setText("Bienvenido!");

        jButton3.setBackground(new java.awt.Color(32, 34, 37));
        jButton3.setFont(new java.awt.Font("STXihei", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 102, 255));
        jButton3.setText("¿Olvidaste tu contraseña?");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        campoContras.setBackground(new java.awt.Color(55, 57, 63));
        campoContras.setFont(new java.awt.Font("STXihei", 0, 16)); // NOI18N
        campoContras.setForeground(new java.awt.Color(234, 234, 235));
        campoContras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 234, 235)));
        campoContras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContrasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("STXihei", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(234, 234, 235));
        jLabel4.setText("Lorem Ipsum");
        jLabel4.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabel4.setName(""); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(700, 100));

        textoPregunta.setFont(new java.awt.Font("STXihei", 1, 16)); // NOI18N
        textoPregunta.setForeground(new java.awt.Color(234, 234, 235));
        textoPregunta.setText("Usuario");

        textoPregunta1.setFont(new java.awt.Font("STXihei", 1, 16)); // NOI18N
        textoPregunta1.setForeground(new java.awt.Color(234, 234, 235));
        textoPregunta1.setText("Contraseña");

        cancelar.setBackground(new java.awt.Color(10, 135, 55));
        cancelar.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        cancelar.setForeground(new java.awt.Color(234, 234, 235));
        cancelar.setText("Entrar");
        cancelar.setFocusPainted(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        cancelar1.setBackground(new java.awt.Color(10, 135, 55));
        cancelar1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        cancelar1.setForeground(new java.awt.Color(234, 234, 235));
        cancelar1.setText("Cancelar");
        cancelar1.setFocusPainted(false);
        cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoPregunta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textoPregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoContras)
                        .addComponent(nomUsuario)
                        .addComponent(jLabel3)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(cancelar)
                            .addGap(43, 43, 43)))
                    .addComponent(bienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(432, 432, 432))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(cancelar1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(textoPregunta)
                .addGap(25, 25, 25)
                .addComponent(nomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(textoPregunta1)
                .addGap(25, 25, 25)
                .addComponent(campoContras, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelar1)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomUsuarioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // boton olvidaste 
            olvCont = new OlvidasteContrasena();
            olvCont.setV1(this);
            olvCont.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void campoContrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContrasActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        String usuario = nomUsuario.getText();
        char[] con = campoContras.getPassword();
        String contra = new String(con);
        bienvenido.setVisible(false);
        jLabel3.setVisible(false);
        if(usuario.equals("") || contra.equals("")){
           jLabel3.setVisible(true);
        }else{
            jLabel3.setVisible(false);
            Usuario user = gestorUsuarios.buscarUsuario(usuario, contra);
            if (user != null) {
                bienvenido.setVisible(true);
                menuUs = new MenuUsuario(user);
                menuUs.setVisible(true);
                this.dispose(); 
            } else {
                jLabel3.setVisible(true);
            }
        
        }
    }//GEN-LAST:event_cancelarActionPerformed

    private void cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar1ActionPerformed
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelar1ActionPerformed
    public void setV1(VentanaInicio v1){
        this.v1 = v1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenido;
    private javax.swing.JPasswordField campoContras;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelar1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nomUsuario;
    private javax.swing.JLabel textoPregunta;
    private javax.swing.JLabel textoPregunta1;
    // End of variables declaration//GEN-END:variables
}
