/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.organizadordetareas.Vista;
import com.mycompany.organizadordetareas.Controlador.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author MSI i7
 */
public class OlvidasteContrasena extends javax.swing.JFrame {

    /**
     * Creates new form OlvidasteContrasena
     */
    private GestorUser gestorUs = new GestorUser();
    private IniciarSesion incSes;
    public OlvidasteContrasena() {
        initComponents();
        textoPregunta.setVisible(false);
        PreguntaSeguridad.setVisible(false);
        cajitaRespuesta.setVisible(false);
        nomUsNoEncontrado.setVisible(false);
        setLocationRelativeTo(null);
        contNoSegura.setVisible(false);
        noCoinciden.setVisible(false);
        campVacios.setVisible(false);
        btExito.setVisible(false);
        resIncor.setVisible(false);
        verificarPreg.setVisible(false);
        // Establecer el tamaño deseado (por ejemplo, 600x400 píxeles)
        jDialog1.setSize(600, 400);

        jDialog1.setLocationRelativeTo(null);

        jDialog1.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        campoContN = new javax.swing.JPasswordField();
        campoContNDeNuevo = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        recuperarBto = new javax.swing.JButton();
        contNoSegura = new javax.swing.JLabel();
        campVacios = new javax.swing.JLabel();
        noCoinciden = new javax.swing.JLabel();
        bt = new javax.swing.JButton();
        btExito = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textoPregunta = new javax.swing.JLabel();
        PreguntaSeguridad = new javax.swing.JLabel();
        textoNombreUs = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cajitaRespuesta = new javax.swing.JTextField();
        nomUsNoEncontrado = new javax.swing.JLabel();
        verificarPreg = new javax.swing.JButton();
        resIncor = new javax.swing.JLabel();

        jDialog1.setPreferredSize(new java.awt.Dimension(700, 200));

        jLabel2.setText("Nueva contraseña");

        campoContN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContNActionPerformed(evt);
            }
        });

        campoContNDeNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContNDeNuevoActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingresa nuevamente");

        jLabel5.setText("Recuperar contraseña");

        recuperarBto.setText("Recuperar");
        recuperarBto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recuperarBtoActionPerformed(evt);
            }
        });

        contNoSegura.setText("La contraseña no es segura");

        campVacios.setText("Llene los campos");

        noCoinciden.setText("Las contraseñas no coinciden");

        bt.setText("Atrás");
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });

        btExito.setText("¡Éxito! Recuperaste tu contraseña");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoContN, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoContNDeNuevo)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recuperarBto)
                                .addGap(12, 12, 12)
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campVacios, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noCoinciden, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contNoSegura, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btExito, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoContN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(contNoSegura)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoContNDeNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recuperarBto)))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(campVacios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noCoinciden)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btExito)
                .addGap(13, 13, 13)
                .addComponent(bt)
                .addGap(28, 28, 28))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Lorem Ipsum");
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(700, 100));

        textoPregunta.setText("Pregunta de seguridad");

        PreguntaSeguridad.setText("jLabel3");

        textoNombreUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreUsActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingresa el nombre de usuario");

        cajitaRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajitaRespuestaActionPerformed(evt);
            }
        });

        nomUsNoEncontrado.setText("Nombre de usuario no encontrado");

        verificarPreg.setText("Verificar");
        verificarPreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarPregActionPerformed(evt);
            }
        });

        resIncor.setText("La respuesta no es correcta, intente de nuevo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PreguntaSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cajitaRespuesta)
                                    .addComponent(textoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoNombreUs)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(nomUsNoEncontrado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(verificarPreg))))
                            .addComponent(resIncor, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(167, 167, 167)))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomUsNoEncontrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNombreUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoPregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PreguntaSeguridad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cajitaRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verificarPreg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resIncor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoNombreUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreUsActionPerformed
        // texto nombre de usuario
    }//GEN-LAST:event_textoNombreUsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // boton para buscar el usuario
        String nomUs = textoNombreUs.getText();
        Usuario us = gestorUs.buscarUsuarioNom(nomUs);
        if(us != null){
            textoPregunta.setVisible(true);
            PreguntaSeguridad.setVisible(true);
            cajitaRespuesta.setVisible(true);
            nomUsNoEncontrado.setVisible(false);
            PreguntaSeguridad.setText(gestorUs.getPreguntaEnPos(us.getIndicePregunta()));
            verificarPreg.setVisible(true);
        }else{
            nomUsNoEncontrado.setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cajitaRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajitaRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajitaRespuestaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //atras
        incSes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void verificarPregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarPregActionPerformed
        // Tverificar
        String nomUs = textoNombreUs.getText();
        Usuario us = gestorUs.buscarUsuarioNom(nomUs);
        String res = cajitaRespuesta.getText();
        if(us.getRespuesta().equals(res)){
            jDialog1.setVisible(true);
            resIncor.setVisible(false);
        }else{
            resIncor.setVisible(true);
        }
        
    }//GEN-LAST:event_verificarPregActionPerformed

    private void recuperarBtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recuperarBtoActionPerformed
        // boton recuperar
        char[] arr = campoContN.getPassword();
        String cont = new String(arr);
        char[] arr2 = campoContNDeNuevo.getPassword();
        String cont2 = new String(arr2);
        String nomUs = textoNombreUs.getText();
        
        if(!cont.isEmpty() && !cont2.isEmpty()){
            if(cont.equals(cont2)){
                if(validarContraSegura(cont)){
                    contNoSegura.setVisible(false);
                    noCoinciden.setVisible(false);
                    campVacios.setVisible(false);
                    btExito.setVisible(true);
                    gestorUs.modificarContraseña(nomUs, cont2);
                    
                }else{
                    contNoSegura.setVisible(true);
                    campVacios.setVisible(false);
                    noCoinciden.setVisible(false);
                }
            }else{
                noCoinciden.setVisible(true);
                campVacios.setVisible(false);
                contNoSegura.setVisible(false);
            }
        }else{
            campVacios.setVisible(true);
            contNoSegura.setVisible(false);
            noCoinciden.setVisible(false);
        }
        
    }//GEN-LAST:event_recuperarBtoActionPerformed

    private void campoContNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContNActionPerformed

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
        // atras
        jDialog1.dispose();

    // Cerrar el JFrame actual
    this.dispose();

    // Crear una instancia del nuevo JFrame "IniciarSesion"
    IniciarSesion iniciarSesionFrame = new IniciarSesion();

    // Mostrar el nuevo JFrame "IniciarSesion"
    iniciarSesionFrame.setVisible(true);
        
        
    }//GEN-LAST:event_btActionPerformed

    private void campoContNDeNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContNDeNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContNDeNuevoActionPerformed

    public  boolean validarContraSegura(String contrasena) {
        // Al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter
        // especial
        String pattern = "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$";

        Pattern p = Pattern.compile(pattern);
        Matcher m = p.matcher(contrasena);

        return m.matches();
    }
    
    public void setV1(IniciarSesion v1){
        this.incSes = v1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OlvidasteContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OlvidasteContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OlvidasteContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OlvidasteContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OlvidasteContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PreguntaSeguridad;
    private javax.swing.JButton bt;
    private javax.swing.JLabel btExito;
    private javax.swing.JTextField cajitaRespuesta;
    private javax.swing.JLabel campVacios;
    private javax.swing.JPasswordField campoContN;
    private javax.swing.JPasswordField campoContNDeNuevo;
    private javax.swing.JLabel contNoSegura;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel noCoinciden;
    private javax.swing.JLabel nomUsNoEncontrado;
    private javax.swing.JButton recuperarBto;
    private javax.swing.JLabel resIncor;
    private javax.swing.JTextField textoNombreUs;
    private javax.swing.JLabel textoPregunta;
    private javax.swing.JButton verificarPreg;
    // End of variables declaration//GEN-END:variables
}
