/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.organizadordetareas.Vista;

import com.mycompany.organizadordetareas.Controlador.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.awt.Color;

/**
 *
 * @author Arrick
 */
public class Registrarse extends javax.swing.JFrame {
    private final GestorUser gestorUsuarios = new GestorUser();
    private VentanaInicio v1;
    private String pregAleatoria;
    private int ind;
    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
        setLocation(400,500);
        setSize(1000,700);
        setResizable(false);
        errContra.setVisible(false); 
        errContras.setVisible(false);
        errUsuario.setVisible(false);
        exito.setVisible(false);
        rellenar_label.setVisible(false);
        ind = (int)(Math.random()*(5) + 1);
        pregAleatoria = gestorUsuarios.getPreguntaEnPos(ind);
        preguntaSeguridad.setText(pregAleatoria);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(55, 57, 63));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_usuario = new javax.swing.JTextField();
        usuarioLabel = new javax.swing.JLabel();
        contraLabel = new javax.swing.JLabel();
        reescribrirLabel = new javax.swing.JLabel();
        errUsuario = new javax.swing.JLabel();
        errContra = new javax.swing.JLabel();
        errContras = new javax.swing.JLabel();
        rellenar_label = new javax.swing.JLabel();
        exito = new javax.swing.JLabel();
        preguntaSeguridad = new javax.swing.JLabel();
        campoResp = new javax.swing.JTextField();
        campoContra1 = new javax.swing.JPasswordField();
        campoContra2 = new javax.swing.JPasswordField();
        cancelar = new javax.swing.JButton();
        cancelar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text_usuario.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        text_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_usuarioActionPerformed(evt);
            }
        });

        usuarioLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        usuarioLabel.setForeground(new java.awt.Color(234, 234, 235));
        usuarioLabel.setText("Usuario");

        contraLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        contraLabel.setForeground(new java.awt.Color(234, 234, 235));
        contraLabel.setText("Escriba una contraseña:");

        reescribrirLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        reescribrirLabel.setForeground(new java.awt.Color(234, 234, 235));
        reescribrirLabel.setText("Reescriba su contraseña:");

        errUsuario.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        errUsuario.setText("Usuario ya existente");

        errContra.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        errContra.setText("La contraseña debe contener al menos 8 caracteres, incluyendo al menos una letra mayúscula, una minúscula, un número y un carácter especial.");

        errContras.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        errContras.setText("Las contraseñas no coinciden");

        rellenar_label.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        rellenar_label.setText("Rellene los espacios por favor");

        exito.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        exito.setText("Excitante");

        preguntaSeguridad.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        preguntaSeguridad.setForeground(new java.awt.Color(234, 234, 235));
        preguntaSeguridad.setText("jLabel1");

        campoResp.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        campoResp.setToolTipText("");
        campoResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRespActionPerformed(evt);
            }
        });

        campoContra1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N

        campoContra2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        campoContra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContra2ActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(10, 135, 55));
        cancelar.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        cancelar.setForeground(new java.awt.Color(234, 234, 235));
        cancelar.setText("Registrarse");
        cancelar.setFocusPainted(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        cancelar1.setBackground(new java.awt.Color(10, 135, 55));
        cancelar1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        cancelar1.setForeground(new java.awt.Color(234, 234, 235));
        cancelar1.setText("Cancelar");
        cancelar1.setFocusPainted(false);
        cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reescribrirLabel)
                            .addComponent(contraLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoContra1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(errContras))
                            .addComponent(campoContra2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 356, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarioLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(errUsuario)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rellenar_label)
                        .addGap(376, 376, 376))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(exito)
                        .addGap(390, 390, 390))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(errContra)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(preguntaSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoResp, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelar)
                .addGap(389, 389, 389))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(cancelar1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioLabel)
                    .addComponent(preguntaSeguridad))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errUsuario)
                    .addComponent(text_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(campoResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contraLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoContra1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(errContras, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addComponent(reescribrirLabel)
                .addGap(18, 18, 18)
                .addComponent(campoContra2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errContra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rellenar_label)
                .addGap(12, 12, 12)
                .addComponent(exito, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(cancelar1)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_usuarioActionPerformed
    
    public  boolean validarContraSegura(String contrasena) {
        // Al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter
        // especial
        String pattern = "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$";

        Pattern p = Pattern.compile(pattern);
        Matcher m = p.matcher(contrasena);

        return m.matches();
    }

    private void campoRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRespActionPerformed

    private void campoContra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContra2ActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        String tex_usuario = text_usuario.getText();
        char [] cont1 = campoContra1.getPassword();
        char [] cont2 = campoContra2.getPassword();
        String tex_contra = new String(cont1);
        String tex_recontra = new String(cont2);
        String textResp = campoResp.getText();
        
        errContra.setVisible(false); 
        errContras.setVisible(false);
        errUsuario.setVisible(false);
        rellenar_label.setVisible(false);
        boolean valida = validarContraSegura(tex_contra);
        if(tex_usuario.equals("") || tex_contra.equals("")||textResp.equals("")){
            rellenar_label.setVisible(true);
        }else{
            if(!valida){             
                errContra.setVisible(true);            
            }else{                
                if(!tex_contra.equals(tex_recontra)){
                    errContras.setVisible(true);
                  
                }else{
                   Usuario user = gestorUsuarios.buscarUsuarioNom(tex_usuario);
                   if (!gestorUsuarios.registrarUsuario(new Usuario(tex_usuario, tex_contra, textResp, ind))) {
                        errUsuario.setVisible(true);
                    } else {
                        exito.setVisible(true);
                        v1.setVisible(true);
                        this.dispose();
                    }
                }
            }
        } 
    }//GEN-LAST:event_cancelarActionPerformed

    private void cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar1ActionPerformed
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelar1ActionPerformed
    public void setV1(VentanaInicio v1){
        this.v1 = v1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField campoContra1;
    private javax.swing.JPasswordField campoContra2;
    private javax.swing.JTextField campoResp;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelar1;
    private javax.swing.JLabel contraLabel;
    private javax.swing.JLabel errContra;
    private javax.swing.JLabel errContras;
    private javax.swing.JLabel errUsuario;
    private javax.swing.JLabel exito;
    private javax.swing.JLabel preguntaSeguridad;
    private javax.swing.JLabel reescribrirLabel;
    private javax.swing.JLabel rellenar_label;
    private javax.swing.JTextField text_usuario;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
