/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.organizadordetareas.Vista;

import com.mycompany.organizadordetareas.Controlador.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.awt.Color;

/**
 *
 * @author Arrick
 */
public class Registrarse extends javax.swing.JFrame {
    private final GestorUser gestorUsuarios = new GestorUser();
    private VentanaInicio v1;
    private String pregAleatoria;
    private int ind;
    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
        setLocation(400,500);
        setSize(1000,700);
        setResizable(false);
        errContra.setVisible(false); 
        errContras.setVisible(false);
        errUsuario.setVisible(false);
        exito.setVisible(false);
        rellenar_label.setVisible(false);
        ind = (int)(Math.random()*(5) + 1);
        pregAleatoria = gestorUsuarios.getPreguntaEnPos(ind);
        preguntaSeguridad.setText(pregAleatoria);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(55, 57, 63));
        
        //LlenarCampos
        llenarCampos.setSize(500,300 );
        llenarCampos.getContentPane().setBackground(new Color(55, 57, 63));
        llenarCampos.setLocationRelativeTo(null);
        llenarCampos.setVisible(false);
        // errorContra
        errorContra.setSize(500,300 );
        errorContra.getContentPane().setBackground(new Color(55, 57, 63));
        errorContra.setLocationRelativeTo(null);
        errorContra.setVisible(false);
        
        //errUsuari
        errUsuari.setSize(500,300 );
        errUsuari.getContentPane().setBackground(new Color(55, 57, 63));
        errUsuari.setLocationRelativeTo(null);
        errUsuari.setVisible(false);
        
        //errContr
        errContr.setSize(500,300 );
        errContr.getContentPane().setBackground(new Color(55, 57, 63));
        errContr.setLocationRelativeTo(null);
        errContr.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        llenarCampos = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        errorContra = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        errUsuari = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        errContr = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        text_usuario = new javax.swing.JTextField();
        usuarioLabel = new javax.swing.JLabel();
        contraLabel = new javax.swing.JLabel();
        reescribrirLabel = new javax.swing.JLabel();
        errUsuario = new javax.swing.JLabel();
        errContra = new javax.swing.JLabel();
        errContras = new javax.swing.JLabel();
        rellenar_label = new javax.swing.JLabel();
        exito = new javax.swing.JLabel();
        preguntaSeguridad = new javax.swing.JLabel();
        campoResp = new javax.swing.JTextField();
        campoContra1 = new javax.swing.JPasswordField();
        campoContra2 = new javax.swing.JPasswordField();
        cancelar = new javax.swing.JButton();
        cancelar1 = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(234, 234, 235));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Complete los campos vacios, por favor.");
        jLabel5.setToolTipText("");
        jLabel5.setMaximumSize(new java.awt.Dimension(400, 300));
        jLabel5.setName(""); // NOI18N

        jButton1.setBackground(new java.awt.Color(32, 34, 37));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(234, 234, 235));
        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout llenarCamposLayout = new javax.swing.GroupLayout(llenarCampos.getContentPane());
        llenarCampos.getContentPane().setLayout(llenarCamposLayout);
        llenarCamposLayout.setHorizontalGroup(
            llenarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(llenarCamposLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, llenarCamposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        llenarCamposLayout.setVerticalGroup(
            llenarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(llenarCamposLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(234, 234, 235));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Las contraseñas no coinciden");
        jLabel2.setToolTipText("");
        jLabel2.setMaximumSize(new java.awt.Dimension(400, 300));
        jLabel2.setName(""); // NOI18N

        jButton4.setBackground(new java.awt.Color(32, 34, 37));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(234, 234, 235));
        jButton4.setText("ACEPTAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout errorContraLayout = new javax.swing.GroupLayout(errorContra.getContentPane());
        errorContra.getContentPane().setLayout(errorContraLayout);
        errorContraLayout.setHorizontalGroup(
            errorContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorContraLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(errorContraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        errorContraLayout.setVerticalGroup(
            errorContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorContraLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton4)
                .addGap(67, 67, 67))
        );

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(234, 234, 235));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ingrese otro por favor.");
        jLabel3.setToolTipText("");
        jLabel3.setName(""); // NOI18N

        jButton3.setBackground(new java.awt.Color(32, 34, 37));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(234, 234, 235));
        jButton3.setText("ACEPTAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(234, 234, 235));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Usuario ya existente,");
        jLabel8.setToolTipText("");
        jLabel8.setName(""); // NOI18N

        javax.swing.GroupLayout errUsuariLayout = new javax.swing.GroupLayout(errUsuari.getContentPane());
        errUsuari.getContentPane().setLayout(errUsuariLayout);
        errUsuariLayout.setHorizontalGroup(
            errUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errUsuariLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(errUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(errUsuariLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        errUsuariLayout.setVerticalGroup(
            errUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errUsuariLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(234, 234, 235));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("La contraseña debe contener al menos ");
        jLabel9.setToolTipText("");
        jLabel9.setMaximumSize(new java.awt.Dimension(400, 300));
        jLabel9.setName(""); // NOI18N

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(234, 234, 235));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("8 caracteres,incluyendo al menos");
        jLabel10.setToolTipText("");
        jLabel10.setMaximumSize(new java.awt.Dimension(400, 300));
        jLabel10.setName(""); // NOI18N

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(234, 234, 235));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("una letra mayúscula, una minúscula,");
        jLabel11.setToolTipText("");
        jLabel11.setMaximumSize(new java.awt.Dimension(400, 300));
        jLabel11.setName(""); // NOI18N

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(234, 234, 235));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("un número y un carácter especial.");
        jLabel12.setToolTipText("");
        jLabel12.setMaximumSize(new java.awt.Dimension(400, 300));
        jLabel12.setName(""); // NOI18N

        jButton5.setBackground(new java.awt.Color(32, 34, 37));
        jButton5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(234, 234, 235));
        jButton5.setText("ACEPTAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout errContrLayout = new javax.swing.GroupLayout(errContr.getContentPane());
        errContr.getContentPane().setLayout(errContrLayout);
        errContrLayout.setHorizontalGroup(
            errContrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errContrLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(errContrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errContrLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        errContrLayout.setVerticalGroup(
            errContrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errContrLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton5)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text_usuario.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        text_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_usuarioActionPerformed(evt);
            }
        });

        usuarioLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        usuarioLabel.setForeground(new java.awt.Color(234, 234, 235));
        usuarioLabel.setText("Usuario");

        contraLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        contraLabel.setForeground(new java.awt.Color(234, 234, 235));
        contraLabel.setText("Escriba una contraseña:");

        reescribrirLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        reescribrirLabel.setForeground(new java.awt.Color(234, 234, 235));
        reescribrirLabel.setText("Reescriba su contraseña:");

        errUsuario.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        errUsuario.setText("Usuario ya existente");

        errContra.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        errContra.setText("La contraseña debe contener al menos 8 caracteres, incluyendo al menos una letra mayúscula, una minúscula, un número y un carácter especial.");

        errContras.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        errContras.setText("Las contraseñas no coinciden");

        rellenar_label.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        rellenar_label.setText("Rellene los espacios por favor");

        exito.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        exito.setText("Excitante");

        preguntaSeguridad.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        preguntaSeguridad.setForeground(new java.awt.Color(234, 234, 235));
        preguntaSeguridad.setText("jLabel1");

        campoResp.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        campoResp.setToolTipText("");
        campoResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRespActionPerformed(evt);
            }
        });

        campoContra1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N

        campoContra2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        campoContra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContra2ActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(10, 135, 55));
        cancelar.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        cancelar.setForeground(new java.awt.Color(234, 234, 235));
        cancelar.setText("Registrarse");
        cancelar.setBorder(null);
        cancelar.setFocusPainted(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        cancelar1.setBackground(new java.awt.Color(32, 34, 37));
        cancelar1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        cancelar1.setForeground(new java.awt.Color(234, 234, 235));
        cancelar1.setText("Cancelar");
        cancelar1.setBorder(null);
        cancelar1.setFocusPainted(false);
        cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reescribrirLabel)
                            .addComponent(contraLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoContra1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(errContras))
                            .addComponent(campoContra2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 356, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarioLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(errUsuario)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(exito)
                        .addGap(390, 390, 390))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(errContra)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(preguntaSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoResp, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rellenar_label)
                        .addGap(376, 376, 376))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(398, 398, 398))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioLabel)
                    .addComponent(preguntaSeguridad))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errUsuario)
                    .addComponent(text_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(campoResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(contraLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoContra1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(errContras, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addComponent(reescribrirLabel)
                .addGap(18, 18, 18)
                .addComponent(campoContra2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errContra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rellenar_label)
                .addGap(12, 12, 12)
                .addComponent(exito, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_usuarioActionPerformed
    
    public  boolean validarContraSegura(String contrasena) {
        // Al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter
        // especial
        String pattern = "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$";

        Pattern p = Pattern.compile(pattern);
        Matcher m = p.matcher(contrasena);

        return m.matches();
    }

    private void campoRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRespActionPerformed

    private void campoContra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContra2ActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        String tex_usuario = text_usuario.getText();
        char [] cont1 = campoContra1.getPassword();
        char [] cont2 = campoContra2.getPassword();
        String tex_contra = new String(cont1);
        String tex_recontra = new String(cont2);
        String textResp = campoResp.getText();
        
        errContra.setVisible(false); 
        errContras.setVisible(false);
        errUsuario.setVisible(false);
        rellenar_label.setVisible(false);
        boolean valida = validarContraSegura(tex_contra);
        if(tex_usuario.equals("") || tex_contra.equals("")||textResp.equals("")){
            llenarCampos.setVisible(true);
            llenarCampos.setLocationRelativeTo(null);
            

        }else{
            if(!valida){ 
                //errContra
                errContr.setVisible(true);
                errContr.setLocationRelativeTo(null);
                // poner en todos 
                            
            }else{                
                if(!tex_contra.equals(tex_recontra)){
                    //errContras  
                    errorContra.setLocationRelativeTo(null);
                    errorContra.setVisible(true);
                  
                }else{
                   Usuario user = gestorUsuarios.buscarUsuarioNom(tex_usuario);
                   if (!gestorUsuarios.registrarUsuario(new Usuario(tex_usuario, tex_contra, textResp, ind))) {
                        //errUsuario
                        errUsuari.setLocationRelativeTo(null);
                        errUsuari.setVisible(true);
                    } else {
                       // exito, registro completado 
                       
                       exito.setVisible(true);
                        v1.setVisible(true);
                        this.dispose();
                    }
                }
            }
        } 
    }//GEN-LAST:event_cancelarActionPerformed

    private void cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar1ActionPerformed
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        llenarCampos.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        errUsuari.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        errorContra.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        errContr.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
    public void setV1(VentanaInicio v1){
        this.v1 = v1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField campoContra1;
    private javax.swing.JPasswordField campoContra2;
    private javax.swing.JTextField campoResp;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelar1;
    private javax.swing.JLabel contraLabel;
    private javax.swing.JDialog errContr;
    private javax.swing.JLabel errContra;
    private javax.swing.JLabel errContras;
    private javax.swing.JDialog errUsuari;
    private javax.swing.JLabel errUsuario;
    private javax.swing.JDialog errorContra;
    private javax.swing.JLabel exito;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JDialog llenarCampos;
    private javax.swing.JLabel preguntaSeguridad;
    private javax.swing.JLabel reescribrirLabel;
    private javax.swing.JLabel rellenar_label;
    private javax.swing.JTextField text_usuario;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
